// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClAXFgLfD5y_lOVITFEdnO0_vq9YbpRjQ',
    appId: '1:600106409191:web:4d7b07c599283b3a001642',
    messagingSenderId: '600106409191',
    projectId: 'mpxoxo-fada0',
    authDomain: 'mpxoxo-fada0.firebaseapp.com',
    databaseURL: 'https://mpxoxo-fada0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mpxoxo-fada0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYUV5IMaBSlQf1fNQOhAz1ewE2vJPuBsU',
    appId: '1:600106409191:android:330ff5fbbbc6f2b7001642',
    messagingSenderId: '600106409191',
    projectId: 'mpxoxo-fada0',
    databaseURL: 'https://mpxoxo-fada0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mpxoxo-fada0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDP4sZHj223yypiJBcVZxgh41ilPzKe9tw',
    appId: '1:600106409191:ios:99576428cf467bb2001642',
    messagingSenderId: '600106409191',
    projectId: 'mpxoxo-fada0',
    databaseURL: 'https://mpxoxo-fada0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mpxoxo-fada0.appspot.com',
    iosClientId: '600106409191-ca2q9iuj6mnmlkg1hp03sr1j44jlmqgj.apps.googleusercontent.com',
    iosBundleId: 'com.example.xo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDP4sZHj223yypiJBcVZxgh41ilPzKe9tw',
    appId: '1:600106409191:ios:99576428cf467bb2001642',
    messagingSenderId: '600106409191',
    projectId: 'mpxoxo-fada0',
    databaseURL: 'https://mpxoxo-fada0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mpxoxo-fada0.appspot.com',
    iosClientId: '600106409191-ca2q9iuj6mnmlkg1hp03sr1j44jlmqgj.apps.googleusercontent.com',
    iosBundleId: 'com.example.xo',
  );
}
